### PR TITLE
Shooting Club DM V0_3

### PR DESCRIPTION
**Pull request by Derek-Asirvadem**
@DanielLoth 

> Is this Normalised ?

Ok, we have started.  At least we need Entity Level, for “conceptualising” the entities (your V0_2).  And then the bulk is done at the Key Level, for which PKs, and optionally AKs, but not FKs (they are obvious) need to be exposed.

Here is my first response Shooting Club V0_3.  A mixed bag:

- responding to your question for the Location, Organisation & Person clusters
- showing you the options to choose from,
[Shooting Club DM V0_3.pdf](https://github.com/DanielLoth/ShootingClubDatabase/files/6877325/Shooting.Club.V0_3.pdf)
 for future DMs
- including IDEF1R, which is much easier; less cumbersome than IDEF1X at the Key Level

Starting with those two clusters, please comment; question; discuss; etc.  

After that discussion, the next step would be for you to create DM V0_4: 
1. the focus is on **what** the entity is
    - this may get into **why** the entity exists
2. then the **identity** of the entity (Identifier; PK; AK) - First Law of Thought - Identity
3. then what other entity it relates to (probably too early at this stage, it will be the effort in the next increment)
    - and specifically Identifying vs Non-Identifying

**Increments**
Rather than drawing up all entities that you can think of, start with a couple of relevant clusters only, get it stable; and then with each increment (version) add an entity or three; get it stable; and so on.  Data modelling is an iterative task.  We will have many versions before we reach V1_0.

Cheers
Derek

### CODE REVIEW

**Comment by DanielLoth** [comment]
Hi Derek,

I'll start with the questions in pull request #4.

---

> What is the distinction between User and Person ?

At the very least, a `Person` is a member of the club XOR a prospective member XOR a guest who is shooting at the club during a competition.
Conceivably it could be a non-shooter who was on-site at the club and therefore needs to be recorded as having visited. Think wives / girlfriends / etc.

A `User` on the other hand is someone with a login. I conceive of `Users` being associated with `Organisations`, with that association affording them the ability to use the software pursuant to the `Roles` granted by the organisation administrator.

Importantly, `Person` is an informational-only concept. An organisation might invite an auditor into their organisation, for example, and of course that auditor would not necessarily have ever shot at or visited the club, and so would not be captured as a `Person` in the system.

So imagine this were a working system. A subscriber signs up on behalf of their club.

That subscriber, in signing up, becomes a `User` and is captured in the data as such. At the same time, they would be creating an `Organisation` as part of the subscription process.

However, both `User` and `Organisation` are independent. I conceive of a system where existing users can be invited into other `Organisations` by the administrators of those organisations, or create multiple `Organisations` if they so wish.

**Comment by DanielLoth** [comment]
> In the V1 model, it is not clear what columns are PK (I appreciate it is not IDEF1X). So it is not clear whether the columns in a child are Identifying or not.

In the [original version](https://github.com/DanielLoth/ShootingClubDatabase/blob/main/Diagrams/Older%20diagrams/Club%20ER%20diagram%20(some%20FK%20constraints%20not%20present).png) the primary keys are represented with the little key icon.

So for example, the primary key for `Competitor` is the following composite key:
- OrganisationId
- CompetitionId
- CompetitorId

And the primary key for a `Grade` is:
- GoverningBodyCode (e.g.: ISSF - I renamed `GoverningBody` to `DisciplineSponsor` in the V0.2 diagram)
- DisciplineCode (e.g.: AP60 - renamed to `DisciplineMatch` in the V0.2 diagram)
- ShooterCohortCode (e.g.: 'M' for 'Male' or 'B' for 'Junior Men')
- GradeCode (e.g.: 'A' for A grade)

The GraphViz file that I put up was an experiment in getting something to work, not a genuine revision. I won't be using GraphViz anymore as it's not easy to establish left-to-right, top-to-bottom hierarchy that I put in the V0.2 diagram.

**Comment by DanielLoth** [comment]
> Second point. However it does appear to be clear from the position you have laid out the hierarchy, but then you have drawn some tables that are Reference only, which are Non-Identifying relations, as subordinates ... but Reference tables (Non-Identifying relations) do not define the hierarchy (positioning), only Identifying relations do.

Yes, I'll try to improve that positioning in the future diagrams.

One thing I noticed with your normalisation of the `Location` cluster is that you could conceivably have the following subdivision key: `AU  NSW  A`.

For that reason, my original modelling conceived `SubdivisionCategory` (named `SubdivisionType` in your diagram) as a dependent entity identified by `Country`.
Though thinking about it now, I don't need to elevate the notion of `SubdivisionType` to being a participant in the key for `Subdivision`.

The identifying versus non-identifying aspect is where it gets tricky for me. Generally speaking, almost everything exists in the context of `Organisation` and so is identified by `Organisation` to some extent.

**Comment by DanielLoth** [comment]
In terms of modelling the `Location` cluster, and the `SubdivisionCategory` entity I mentioned, can discriminators / classifiers exist as dependent entities?

For example, like this:
image

At that point, are they just regular entities? Or are they still a discriminator / classifier of sorts?

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> So imagine this were a working system. 

Yes, that is the whole point.  We are not doing a stupefying academic exercise or classroom exercise, which is highly contrived and not based on reality.  We are doing a Data Modelling exercise that is based on reality.

Somewhere you mentioned limiting the scope based on _what the app needs_.  No.  That is a common error.  The data is independent of the app, in fact the database is independent of _all_ apps that may access it, now, and in the future.  So we model the data based on reality, not what the app needs, not what a developer perceives from an app context.

This ensures that the **structure** of the data in the database is stable; solid, and thus when the database is expanded, the changes are merely addition of columns to existing tables or added tables: no effect on existing apps.  Otherwise, every expansion does change the **structure** of the data, and thus existing apps have to change.

The principle is this: the structure of the universe [**Form**] does not change (it is permanent, and has been since its creation).  The content [**Matter**] does change: people get married; auditors are added; addresses change; etc.  But the **structure**, the definition of a Person; the definition of Address, does not change.

Of course, we do not have to define Person to satisfy the needs of the entire planet (eg. 12 tables; 50 columns), we define a subset of that, but when we do define it, we define the structure properly (eg. 4 tables; 20 columns, not 1 table; 10 columns).

> > What is the distinction between User and Person ?
> 
> At the very least, a `Person` is a member of the club XOR a prospective member XOR a guest who is shooting at the club during a competition.
> Conceivably it could be a non-shooter who was on-site at the club and therefore needs to be recorded as having visited. Think wives / girlfriends / etc.
> 
> A `User` on the other hand is someone with a login. I conceive of `Users` being associated with `Organisations`, with that association affording them the ability to use the software pursuant to the `Roles` granted by the organisation administrator.
> 
> Importantly, `Person` is an informational-only concept. An organisation might invite an auditor into their organisation, for example, and of course that auditor would not necessarily have ever shot at or visited the club, and so would not be captured as a `Person` in the system.

Why not ?

Why is an User (any User) not a Person ?

Person is not "info-only".  Person exists, independent of the app.  An User has to first be a Person, and second, a Member in some Organisation.  Or third, an User of the system

This pertains to Normalisation as well.  We want the Person's mobile phone and address recorded once only, that would be in Person.

If we model reality, an Auditor is (a) a Person (b) an User in a particular Organisation [the gun club he is auditing], and (c) has the Role of Auditor.

> So imagine this were a working system. A subscriber signs up on behalf of their club.
> 
> That subscriber, in signing up, becomes a `User` and is captured in the data as such. At the same time, they would be creating an `Organisation` as part of the subscription process.

Yes, but Person first.

And Subscriber is an Organisation, that has that first User.  Subscriber is not an independent User..

> However, both `User` and `Organisation` are independent. I conceive of a system where existing users can be invited into other `Organisations` by the administrators of those organisations, or create multiple `Organisations` if they so wish.

(Maintaining your requirement, and that of reality, but not of any one conception.)  
No.  Person and Organisation are independent.  User is dependent on Organisation, with Roles.  An User who is invited to another Organisation is an User in that Organisation, with an invitee Role[s].

> or create multiple `Organisations` 

I don't understand that.

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> The identifying versus non-identifying aspect is where it gets tricky for me. 

I really should give the course lecture, so that you understand it from the top down.  In the course, I give a run-down on Aristotle; the Four (not three) Laws of Thought; correct thinking, before giving a definition.  Can't do that here.  

For us here, the _Relational Model_ comes first, then IDEF1X which is its half-baked modelling standard.  Please see if you get anything from the [IDEF1X Introduction](https://www.softwaregems.com.au/Documents/Documentary%20Examples/IDEF1X%20Introduction.pdf), and the [Order Advanced](https://www.softwaregems.com.au/Documents/Documentary%20Examples/Order%20DM%20Advanced.pdf) Data Model.

For starters, any subordinate thing that actually belongs to, does not exist without, some parent thing, is **Identifying**.  Eg. an OrderSale is _not_ independent, it exists only in the context of a Party, which is an Individual xor a Corporation.  It belongs to, and therefore is contained in, the Extension (Logic term, look it up), of a Party.  Solid line.  Parent PK is included in the subordinate PK.

Whereas for Reference parents, the child does not belong to, is not contained in, [the Extension of] the parent.  Eg.  OrderSale does not belong to PartyAddress, but it needs a PartyAddress to ship to.  **Non-Identifying**.  Dashed line.  Parent PK is not in the child PK.

> Generally speaking, almost everything exists in the context of `Organisation` and so is identified by `Organisation` to some extent.

That is fine.  Not "to some extent", but explicitly,  If Organisation is required downstream, it must Identifying in that instance.

**Comment by DanielLoth** [comment]
Hi Derek,

Thanks for the replies.

I'll have a go at putting my V0.4 diagram together tonight. I'll look to start with a revision of the `Person` cluster and `Location` cluster.

I'll also answer some of the questions you've put forward.

Cheers,
Dan

**Comment by DanielLoth** [comment]
> Yes, that is the whole point. We are not doing a stupefying academic exercise or classroom exercise, which is highly contrived and not based on reality. We are doing a Data Modelling exercise that is based on reality.
>
> Somewhere you mentioned limiting the scope based on what the app needs. No. That is a common error. The data is independent of the app, in fact the database is independent of all apps that may access it, now, and in the future. So we model the data based on reality, not what the app needs, not what a developer perceives from an app context.
>
> This ensures that the structure of the data in the database is stable; solid, and thus when the database is expanded, the changes are merely addition of columns to existing tables or added tables: no effect on existing apps. Otherwise, every expansion does change the structure of the data, and thus existing apps have to change.
>
> The principle is this: the structure of the universe [Form] does not change (it is permanent, and has been since its creation). The content [Matter] does change: people get married; auditors are added; addresses change; etc. But the structure, the definition of a Person; the definition of Address, does not change.
>
> Of course, we do not have to define Person to satisfy the needs of the entire planet (eg. 12 tables; 50 columns), we define a subset of that, but when we do define it, we define the structure properly (eg. 4 tables; 20 columns, not 1 table; 10 columns).

This is fair, and I agree. To that end, I'll look to model the notion of `Person` so that it can have a minimum amount of information and the full suite of information, with the notion of `User` falling within the `Person` cluster.

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> In terms of modelling the `Location` cluster, and the `SubdivisionCategory` entity I mentioned, can discriminators / classifiers exist as dependent entities?

In general, Reference or LookUp table are Independent (exception, they might be a small hierarchy, the top of which is Independent in any case).  The relations to child tables are Non-Identifying, that is its defining feature.  For IDEF1R modelling purposes, they are further classified for simplicity, into:
- [D]iscriminator, for Basetypes only, which is why the full definition is not required at the Key Level
- [C]lassifier, which is the most common and easily understood, which is why the full definition is not required at the Key Level
- [R] other Reference, not [D] or [C].

Reference tables are not as relevant as "regular" tables, so the symbol is a smaller size.  Usually grey, again denoting Reference.

> For example, like this:
> image
> 
> At that point, are they just regular entities? Or are they still a discriminator / classifier of sorts?

Good progress.

First, SubdivisionType is a [C]lassifier.

_Legislates_ is correct.

Second, because the relation `Country legislates CountrySubdivisionType` is Identifying, CountrySubdivisionType belongs to, it is dependent on, Country.  It is no longer a Reference table in that classification, it is now a "regular" entity, more precisely, a Dependent or Hierarchic entity, in the Country hierarchy.  

Third, it is not Independent, but Dependent, the symbol should have rounded corners.  It is not a [C][D][R].

Fourth, Subdivision is Dependent, it should likewise have rounded corners.

Last, since orange is the colour for Country, SubdivisionType should be not-orange, but grey (my standard) for Reference.

image

In the general case, when the classification [C][D][R] above is understood, there is no need for the VerbPhrases _Classifies; Discriminates_.  But here, note that the relation `SubdivisionType classifies CountrySubdivisionType` is now Identifying.

Cheers
Derek

**Comment by DanielLoth** [comment]
So as a follow-on to that, the original cluster for `Location` was such that `Location IsOneOf Country XOR Subdivision`.
The original intent here is to capture the fact that either a Country or a Subdivision (or both) can prescribe legislative requirements.

In NZ, it'd be the country prescribing requirements.
In AU, it's the purview of states/territories, and so requirements are prescribed in state/territory legislation.

The revised model will need to reflect this change, so I anticipate that there will be far more basetype-subtype clusters.

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> I'll look to model the notion of `Person` so that it can have a minimum amount of information and the full suite of information, with the notion of `User` falling within the `Person` cluster.

Not saying this for certain, as only you know the requirement, and you are the modeller. From what I do understand of that, thus far, I would expect `User` to be subordinate 1::0-1 to `OrganisationPerson`.  An Optional fact about `OrganisationPerson`.

Any fact (table) and its optional facts (tables) are the **Intension** (Logic term, look it up) of that fact.  In contrast to the **Extension**, which contains its subordinate 1::{0|1}-n facts.

(If you have read anthing about Intension; Extension from the Date; Darwen; Fagin asylum, note that they pervery the ancient Logic definition, and erase it from your mind.

**Fact**
Don't think in terms of modelling data, which are fragments, think in terms of modelling Facts that are required, which are Atoms.  The PK is the Fact, the Fact is the PK (as you proceed, you will learn, the absolute importance of the Relational Key).  The attributes are properties of the Fact, they are not Facts themselves.  An optional table is the physical rendition, and must needs be outside the Fact table, but it is logically in the Intension of the Fact.  The Atom is the Intension.

The data model is a logic map, of FOPC Predicates.   I will give you each increment, as and when it comes up.

Logic is a natural language, eg "The original intent here is to capture the _fact_ that ..."

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> So as a follow-on to that, the original cluster for `Location` was such that `Location IsOneOf Country XOR Subdivision`.
> The original intent here is to capture the fact that either a Country or a Subdivision (or both) can prescribe legislative requirements.

I don't know enough about the purpose of `Location` to respond.

We may not need to model _either a Country or a Subdivision (or both) can prescribe legislative requirements_.

> The revised model will need to reflect this change, so I anticipate that there will be far more basetype-subtype clusters.

If it is logically required, it is logically required.  No argument from me.

Cheers
Derek

**Comment by DanielLoth** [comment]
I've just added a V0_4 diagram.

---

So one thing I'm trying to figure out is how the `Person` will work now that it is no longer 'owned' solely by any one organisation.
For example, if Organisation A and Organisation B both have a relationship with Person A, and one of them vandalises the data.

How would you go about dealing with that kind of issue?

---

Another thing, I found that `User` isn't really in the `Person` cluster. I ran into a situation where it kinda felt like I was wanting to mix exclusive and non-exclusive basetype-subtype relationships.

---

Finally, one other thing that occurred to me was that really I want an email address to be mandatory for all `Persons` who happen to also be `Users`. After all, I need to validate the `User` is real.

**Comment by DanielLoth** [comment]
I think I'll make a quick amendment to V0_4.

**Comment by DanielLoth** [comment]
Just a heads-up - dashed lines are hard to see in the PDF unless you zoom in.

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

1.
Why does a `Person` progress first to an `User`, and second to an `OrganisationUser` ?   
Would it not be, that a `Person` progresses to `OrganisationPerson`, let's say `OrganisationMember,` and in that capacity (not without), progresses to `OrganisationUser`

> So one thing I'm trying to figure out is how the Person will work now that it is no longer 'owned' solely by any one organisation.  

Let's take any uncertainty about that and eliminate it.  The Law of the Excluded Middle.  It has to be resolved such that we are never going back there.  In reality, a person's existential reality is independent, right ?  An organisation's existential reality is independent.  The fact of a person being a member of an organisation is subordinate to both, dependent on both.  Except for criminal organisations, no organisation owns a person.

We want only `PersonFulls` to be `OrganisationMembers`, right ?

> For example, if Organisation A and Organisation B both have a relationship with Person A, and one of them vandalises the data.  How would you go about dealing with that kind of issue?

That would break both database and security rules.  Each organisation can vandalise only their own data.  Only a Person can vandalise his own data.

> Finally, one other thing that occurred to me was that really I want an email address to be mandatory for all Persons who happen to also be Users. After all, I need to validate the User is real.

You want `PersonFull` to have a mandatory email (oldies may not have an email), or `OrganisationUser` to have a mandatory email ?

> Just a heads-up - dashed lines are hard to see in the PDF unless you zoom in.

For all lines, increase the Stroke size and set the colour to dark grey.

Cheers
Derek

**Pull request merged**
