### PR TITLE
Shooting Club DM V0_6

### PR DESCRIPTION
**Pull request by DanielLoth**
Hi @Derek-Asirvadem,

I've just added this revision of the diagram. Quite a bit of additional work has gone into this one.

Given your remark about email addresses not necessarily being something that older club members might have, I've re-worked my idea to permit sign in via either a mobile phone number or an email address. I have currently referred to this as a `ContactInstrument` for want of a better term.
I'm not sure what the key would be such that it can be migrated to both the `Email` and `MobileNumber` entity subtypes that fall under the `ContactInstrument` base type.

As per your feedback in V0_5, `Person` has remained an independent entity.
Could you confirm that I've used the diamond correctly? That is, it signifies mandatory attributes.

I have not yet reconciled how I might control access to a Person's data.
However given that this is a compliance system of record, and that GDPR's 'Right to be Forgotten' is a qualified right, I might come back to that later.
Having said that, I suppose the most credible solution would be that the notion of an Access Grant is aligned with a Reporting Year, which ensures that clubs who have recently departed members can still furnish reports up to and including End of Reporting Year.

I've omitted `RoleCode` for the moment.

I've also done my best to rectify the dashed line issue. I couldn't find a way to control stroke size, so switched it to be a dotted line.

Cheers,
Dan

### CODE REVIEW

**Comment by DanielLoth** [comment]
Also, I just realised I should have restructured the diagramming of `PersonPartialEmail` but didn't. I'll save fixing that for my V_08 diagram.

**Comment by DanielLoth** [comment]
> Optionally, if you are dead-set on the ex-organisation not seeing the ex-member's new name, we can do that. There are a few methods.

Thinking about it some more, and with consideration for what you said, perhaps it isn't strictly necessary.

But I can think of situations where someone who has been associated with an organisation in the past might legitimately want to make a clean break from that organisation. For example, a victim of violence who suspects that a sympathiser of their abuser has access to the system.

Or perhaps a much more benign situation: Someone who has gotten the shits with people at a particular club and who at the very least might like to withhold their contact details from that club now that they've relocated to a new club.

In either case, such a person wouldn't want to be 'anchored' to an organisation.

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> Person must have at least one of {Email; MobilePhone}

I think you may find that that may wll be true, but they may not want to give it out.  Eg. after the first year, and getting masses of email from my club, I removed my email from the club records.  Eg. Many oldies may not have an email, or have an email, but do not want to give it out.  If this is an electronic-only system (confirm the KeyCode sent) then sure, one is mandatory.

> But they could have multiple

Sure, that is the real world.
But [for our scope] we need only one of {Email; MobilePhone; Both}, which they say they want to be contacted on.  Ie. they do not really want to be contacted on two or more.  If we have more than one, then one has to be indicated as Primary. Where secondaries are allowed, they are seldom maintained (kept up-to-date).

> Exactly one OrganisationMember must be the OrganisationSubscriber

Subscribing to what ?
I think you mean The System.
Ok.
But would that be a Member who is an (the) User ?

If a Subscriber is one User, and an User is a Member, then I think User = Subscriber.
Otherwise, what is the distinction between Subscriber and User ?

> Not sure how to model this

OrganisationUser would be an optional table from OrganisationMember
The Predicate would be `[Each] OrganisationMember is 0-or-1 OrganisationUser` [The Subscriber].
Then, `OrganisationUser.AK( OrganisationNo )`.

> InternationalCallingCode

Think about this.  It is an attribute of Country.

> Two usages of ContactInstrumentType

No problem, quite ordinary.
But it should be one instance (with two relations).

> Diamond

Yes, that is correct.

> Person.LoginName

Wouldn't that be in OrganisationSubscriber ?

For the next iteration, could you please:
1. make the rounded squares more rounded
2. increase the FontSize for both title and attribute (or leave the FontSize as is, and make the symbols smaller)

More tomorrow.

Cheers
Derek

**Comment by DanielLoth** [comment]
Hi Derek,

> Wouldn't that be in OrganisationSubscriber ?

I don't think my data model revisions so far properly convey what I'm aspiring for in terms of how the system might be used.

Imagine this system is created and provided at some site, say https://www.example.com.

Joe Subscriber from Canberra National Pistol Club (CNPC) finds out about the system and signs up on the club's behalf. He subscribes using his personal credit card, and the club reimburses him.

CNPC decide that they'll allow their members to self-service. So each member, at that member's choosing, can be invited to create a system login.

For this, Joe Subscriber as the Administrator will need to procure either a mobile phone number or an email address from each member who wants access if one isn't already recorded in club records, associate that information with their member record in the system, and then instruct the system to dispatch an invitation to the member so that they may sign up.

Given that they're being invited into an existing organisation, the sign up flow will be different to the sign up flow that Joe Subscriber experienced.

Specifically, Joe Subscriber had to provide all of the information to satisfy the requirements of `PersonFull` in the model above along with information, such as credit card number, to pay the ongoing subscription fee.

(Side note: This is the source of my concern that `PersonFull`, rather than `Person`, underpins the notion of `Subscriber`. It adds information hurdles to the sign up process by calling for relatively personal information to be furnished to a system that they haven't yet had the chance to examine, test, and grow to trust).

These members, on the other hand, have already had those details entered into the system by Joe Subscriber.
So when they receive an invitation link, they'll just need to enter a login name and password. And because this invitation has been sent by Joe working within the context of the organisation, the system will automatically associate their new login with the `Organisation` and their `Person` record.

At this point, these members can self-serve. They can record the dates they visit the club premises, the matches they shoot, and the scores they record in those matches.
Members who do not want to use the system continue to create records in the paper-based systems that exist, as they always have. Joe Subscriber, with assistance from Jane Treasurer, dutifully re-key the contents of the paper-based system into this new online system as they now regard the online system as the source of truth.

(Side note: Future DM revisions would ideally include the notion of approval of claimed visits / participation by someone in a trusted role within the system. Essentially, members self-serve by requesting that a visit / participation be recorded, and the trusted role-holder approves or rejects that request to record the information).

Moving on.

Majura Park Gun Club (MPGC) hear about the success of the system used by CNPC by word-of-mouth. Joe Subscriber is well-known in the sport shooting community in Canberra, and a good friend of the President of MPGC.

The MPGC president expresses an interest in subscribing to the new system, but notes that the club's membership lacks someone who is interested in administrating the new software owing either to lack of interest, lack of time, or lack of computer savvy.

Joe Subscriber helpfully offers to subscribe on behalf of MPGC, and the MPGC president accepts his offer.

Joe signs into the system and creates a second organisation, this one for MPGC. To do this he once again needs to provide payment details, and some basic information about the new organisation.

Joe then adds information for each member of MPGC, making note of any absent information so that it can be retrieved from those members at a later time.

The MPGC membership continue to use their paper-based records, and for the first few months Joe re-keys this information into the system. In return, MPGC reimburse him for the cost of their subscription and additionally pay him a stipend for the ongoing data entry.

Later, a new member named Adam joins MPGC. He's quite happy to help with the data entry, so Joe gives him a role within the MPGC organisation within the system to allow him to do that.
Joe continues to maintain the subscription on their behalf.

---

Hopefully that bit of narrative better explains what I'm going for.

Cheers,
Dan

**Comment by Derek-Asirvadem** [comment]
**Re Shooting Club V0_6**

**Address**
Sooner or later you will have to deal with Address.  That is called for soon, because you have facts that imply Address (PersonFull needs one; ContactMobileNumber implies a Country via InternationalCallingCode; PersonBirthPlace needs one; etc).  We can:
- either keep what we have, and extend it to include County; Town; Street; etc. (given in V0_7 not yet complete)
- or accept that the Address cluster will be loaded from PostOffice source, which is already validated.  Thus we can keep it simple, along the lines of this Address:
[Order Advanced DM](https://www.softwaregems.com.au/Documents/Documentary%20Examples/Order%20DM%20Advanced.pdf)

> SubdivisionType

It is used to form the PK of CountrySubdivisionType.  Therefore it is no longer a Reference (which is characterised by having only Non-Identifying relations).  Since it has Identifying relations, it is an ordinary fact, in this case an Independent.

> Given your remark about email addresses not necessarily being something that older club members might have, I've re-worked my idea to permit sign in via either a mobile phone number or an email address. I have currently referred to this as a `ContactInstrument` for want of a better term.
> I'm not sure what the key would be such that it can be migrated to both the `Email` and `MobileNumber` entity subtypes that fall under the `ContactInstrument` base type.

No problem.

Note, we already have `PersonPartialEmail`.

My question is, why is `ContactInstrument` an Independent fact ?  That is to say, we don't collect `ContactInstruments` independently, we collect them only for `Persons`.  Probably `PersonPartial`.  If you want the Email or the MobilePhoneNo to be unique, no problem, just add an AK. 

In general, if attributes are going to be added piecemeal to `PersonPartial`, and we don't want duplicates, we can deem `PersonFull` as constrained to be full only when all the required attributes are filled in `PersonPartial`.

> I've omitted `RoleCode` for the moment.

That is not a good idea, because we are modelling Person/User/Subscriber, which it classifies.

> I've also done my best to rectify the dashed line issue. I couldn't find a way to control stroke size, so switched it to be a dotted line.

Looks good.

Cheers
Derek

**Pull request merged**
