### PR TITLE
Shooting Club DM V0_5 • Key Level

### PR DESCRIPTION
**Pull request by Derek-Asirvadem**
@DanielLoth 

I expect this answers your questions.  And allows you to ponder two options.

[Shooting Club V0_5.pdf](https://github.com/DanielLoth/ShootingClubDatabase/files/6884995/Shooting.Club.V0_5.pdf)

Cheers
Derek

### CODE REVIEW

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

I am not entriely happy with GitHub, it is messy.  Could you please confirm, you can see that I have posted [Shooting Club V0_5](https://github.com/DanielLoth/ShootingClubDatabase/files/6884995/Shooting.Club.V0_5.pdf) a couple of days ago.

Cheers
Derek

**Comment by DanielLoth** [comment]
Hi Derek,

Yeah I've seen this. I was quite busy with work yesterday so didn't respond.

Cheers,
Dan

**Comment by DanielLoth** [comment]
Hi Derek,

I likely won't be able to create an updated model until the weekend.

However, I have looked at your V0_5 version.

Having thought about it, I still have concerns about the notion of `Person` existing outside of `Organisation`.

There are a few reasons:
1. The legislation, at least in NSW, provides for the fact that a `Person` might belong to more than one `Organisation`. The legislation describes the notion of a primary club. The primary club is the club to report on an individual's compliance or non-compliance during the reporting year.
   - Your proposed structure supports this.
2. The post-GDPR world complicates the notion of data ownership.
   - In an online SaaS application (e.g.: Xero), the subscriber is the so-called GDPR Data Controller. They're the one who elicits personal information and enters it into the system. Xero merely provides the platform, occupying the role of GDPR Data Processor.
   - If the application insists on certain information as part of the sign-up process, then that's the application eliciting the information and therefore the application occupies the role of Data Controller instead of merely Data Processor.

If `Person` exists as an independent entity, there are a number of challenges:
1. What if a `Person` wishes to withdraw from one `Organisation` and not another `Organisation`?
2. What if a `Person` who has left one `Organisation` does not want that organisation to see any future changes to their details (e.g.: name) because their relationship with that organisation is no longer ongoing?
3. What are your thoughts on the GDPR concerns mentioned above?

Cheers,
Dan

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> Having thought about it, I still have concerns about the notion of Person existing outside of Organisation.

First, leave GDPR considerations for later, they will be resolve.

Second, it is important to model [absolute] reality, not reality within the context of a shooting or GDPR.  A person exists independent of any organisation.  That he may or may not later become a member of.

> If Person exists as an independent entity, there are a number of challenges:

No.  Not for FOPC.  Not for the _RM_.  Not for me.

> What if a Person wishes to withdraw from one Organisation and not another Organisation?

That is just one reason why a Person is Independent.

> What if a Person who has left one Organisation does not want that organisation to see any future changes to their details (e.g.: name) because their relationship with that organisation is no longer ongoing?

That is just another reason why a Person is Independent.
The ex-organisation should **not** see an ongoing activity of the person.  That would be the default operation.

But when it comes to Identity (Reality; Key; Fact), that is a higher-level, legal, and database-wide issue.  If the person is Independent, a name change for an ex-member would show up in the ex-organisation, and rightly so.  
- You would not want the ex-member showing up under the new name and getting registered as such.
- You would not want other organisations using the new name, who call the ex-organisation for a referral, to be told that that Person was not a member.
- No, in Australia, a name change is a public document, and the person cannot use their previous name.

Optionally, if you are dead-set on the ex-organisation **not** seeing the ex-member's new name, we can do that.  There are a few methods.

**GDPR**
There are several issuees with GDPR.  Eg. it conflicts established copyright law in Western countries.  Eg. most countries are moving towards a model wherein the person, not the organisation, not the app that enters the data, not the ISP, owns their data.  Eg. America and India have settled legally on a model in which _the country owns the data_, and personal data must not be hosted outside the country.  More countries will follow that. Big Tech is fighting that, but they will lose.

The bun fight is really about [foreign] big tech not only capturing, but holding, personal data, from international users, eg. Fakebook.  That will get resolved, and the fallout will be changed laws.

Cheers
Derek

**Comment by DanielLoth** [comment]
Sorry, re-aligned the branches and it looks like doing so has closed the pull request. I'll be revising my model based on your feedback on the most recent comment along with the provided V0_5 diagram.

**Comment by DanielLoth** [comment]
I've created #7 with the new revision V0_6.

**Pull request merged**
