### PR TITLE
Shooting Club V0_9

### PR DESCRIPTION
**Pull request by Derek-Asirvadem**
**[Shooting Club V0_9.pdf](https://github.com/DanielLoth/ShootingClubDatabase/files/6912546/Shooting.Club.V0_9.pdf)**

> I think in the next rendition we might add an `OrganisationMemberGuest`, with a `(LastName, FirstName)` only. That holds the `Organisation` affiliation. Then let the member log in and register, and enter all their own info, making it up to a `PersonFull`. That will resolve some of those [_who entered the data, who owns the data_] issues.

Done.  `OrganisationInvitee`.

Cheers
Derek

### CODE REVIEW

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

An aside.  If you don't mind, I need to progress and close the c.d.t thread, to provide the finished Template.  If and when you have time.

Cheers
Derek

**Comment by DanielLoth** [comment]
> @DanielLoth
> 
> An aside. If you don't mind, I need to progress and close the c.d.t thread, to provide the finished Template. If and when you have time.
> 
> Cheers
> Derek

Just posted.

**Comment by DanielLoth** [comment]
Hi Derek,

---

Following on from the V0_7 thread, I've been using `Subscriber` to mean the person paying the monthly subscription fee, which is why there's exactly one.

I think you see the `Subscriber` as being the club. So I'm thinking benefactor and you're thinking beneficiary.

---

> I don't think that will ever happen. Clubs are private affairs, and protective of their Members and their Member data. Clubs compete with each other. If not, members compete with members of other clubs, and keep their own friendly 'postal' scores (I did, for American matches). As you mentioned, often there are conflicts, and a member leaves one club, to join another. They do not want info shared.

Fair point of view.

---

Regarding the expanded Country / Subdivision hierarchy, I don't think that's necessary.

Country and subdivision are adequate for place of birth.

Country and subdivision are also adequate for the regulations that different jurisdictions prescribe.

And country alone is enough for the international calling code.

---

I agree that it'd make sense to keep `Address` simple by procuring this data from Australia Post (in Australia) and similar organisations elsewhere.

---

I think at the moment this model is capturing everything discussed. However, if we were to take the approach that only Scorers and the Administrator can record information then it might make more sense to not invite others members into the system in the first place as I had originally envisioned.

---

Cheers,
Dan

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> Following on from the V0_7 thread, I've been using `Subscriber` to mean the person paying the monthly subscription fee, which is why there's exactly one.
> 
> I think you see the `Subscriber` as being the club. So I'm thinking benefactor and you're thinking beneficiary.

Ok.  But even though it is one person who subscribes to the system, it is the club that he subscribes.  If he dies or leaves the club, the subscription survives for the paid period.  Thus the subscriber person is a Member, with Role Admin.  We can have a Role of Subscriber if you prefer.

> Regarding the expanded Country / Subdivision hierarchy, I don't think that's necessary.
> 
> Country and subdivision are adequate for place of birth.
> 
> Country and subdivision are also adequate for the regulations that different jurisdictions prescribe.
> 
> And country alone is enough for the international calling code.

Ok.

> I agree that it'd make sense to keep `Address` simple by procuring this data from Australia Post (in Australia) and similar organisations elsewhere.

Whoa.  But then you (Country + Subdivision) won't work, you need at least a simple 5-level structure ala [Order DM Advanced](https://www.softwaregems.com.au/Documents/Documentary%20Examples/Order%20DM%20Advanced.pdf).

> I think at the moment this model is capturing everything discussed. However, if we were to take the approach that only Scorers and the Administrator can record information then it might make more sense to not invite others members into the system in the first place as I had originally envisioned.

I don't know what pipe dreams you have about this project.  As I light my pipe, it occurs to me immediately that the long term value is for members to obtain various reports on the matches and competitions (a) in their club, and (b) across clubs.  And (c) that is what you should be charging for: a small membership fee for say one year.  Small fee times many members, year after year.  Say $25-50 pa.

The secondary value, but implemented first, it the entire club set up, which gets them off the paper system, and once they are hooked, they are hooked.  Slightly larger club level [subscription] fee.  Say $200-300 pa.

In order to obtain those club subscriptions, the main thing you need to attract them is, a proper set up of all the common Disciplines and Matches.  Other than modelling and coding, this would be the task that you spend substantial time on.  This is where the most mistakes and misunderstandings happen at the club level.  Thus having a perfect set up for all matches, that the club cannot mess up, would be a huge benefit.

Then the club needs to only enter their actual scheduled matches and activities, using drop-downs from the Disciplines and Matches above.  Print off their scheduled matches (spreadsheet with matches and planned cohorts but not scores) and post them on the bulletin board.  After the matches, enter their scores, print off the scheduled matches (spreadsheet with matches and actual cohorts and scores), and stick that on the bulletin board.  [Thus far, it emulated the paper systems currently in use.]  

Following that any Member can log in, view the club level (or state level or national level) scores and stats.  They can also view history, evaluate how they have improved or not, etc.

The database is the heart of any system.  You don't need an app, just webpages with proper GUIs.

----

So we still need a way to:
- add Members and prevent non-Members
- but not force the club Admin/Subscriber to enter all info for all Members
- which means the OrganisationInvitee structure
- which allows each Member to (a) pay a membership fee, and (b) enter all personal info, so that he is (c) a PersonFull, and (d) established as an OrganisationMember.

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Just a heads up, re availability over the next few weeks.  In general, I am available about half time (eg ~20 hours per week).  I am running a court case, they give me demands that have to be filled, at short notice or without notice.  Eg. as of yesterdays cob orders, I have to submit yet another doc by 9 Aug.  The Hearing is on 11 Aug, but that may get cancelled (the defendant appears to be folding).  So I will be available sparsely over the weekend, and back to this properly, on 10 or 12 Aug.

In the removed comments, you gave links that were relevant to understanding DIsciplines; Matches; etc.  Please provide.

Cheers
Derek

**Comment by DanielLoth** [comment]
Hi Derek,

Thanks for your help so far.

No worries re: availability. I've been a bit busy with work myself, so haven't made another increment of this model anyway.

> I don't know what pipe dreams you have about this project. As I light my pipe, it occurs to me immediately that the long term value is for members to obtain various reports on the matches and competitions (a) in their club, and (b) across clubs. And (c) that is what you should be charging for: a small membership fee for say one year. Small fee times many members, year after year. Say $25-50 pa.

Yes. To be clear, I meant that I feel the current iteration is workable in terms of how it's modelling Organisations / People / Users.
My earlier models include those other aspects, such as competition management, match scoring, etc.

I'll put together those links in a future comment.

Cheers,
Dan

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Ok.

> Thanks for your help so far.

My pleasure.  You are easy to work with.

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

I posted some comments in the `Visit_Add_tr.sql` thread.  But I can't get "@Dan" to work ther (it works here).  Looks like GitHub bat-poop.  This is just a ping to that thread.

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> The Hearing is on 11 Aug, but that may get cancelled (the defendant appears to be folding)

They folded.  But they are such dishonest, disgusting c__nts that they left the problem unresolved.  So now, rather than wait for their rigmarole, which is badly constructed,  to start again, I have to lodge a claim which is properly constructed, and thus avoid the rigmarole.  Has to be done before 21 Aug.  This means I am fine, I will be available half-time until further notice.

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Holy sheeeet.  I tried to update `Visit_Add_tr.sql` with `Visit_Add_tr_DA.sql`, which did not work as I expected ... fiddled around ... deleted what I thought was mine ... didn't know wtf a `Gist` was (never saw it before), thought it was what was on the page, which was my upgraded code, but the little freak deleted what seems to be the whole thread.  The GitHub interface is horrible.  

Meaning, I can't find the original, I believe i deleted your Gist.  **Sorry**.  I think I know what a Gist is now.

My upgrade is here:
    [Visit_Add_tr_DA.sql](https://www.softwaregems.com.au/Documents/Article/Database/Transaction/Visit_Add_tr%20DA.sql)

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

I still can't believe that in GitHub, it allows me to delete your Gist.

How do we recover ?  I will take instructions from you.  Your link from c_d_t, your call.  To close off the c_d_t thread, and to have a complete set of code that people can obtain, we need:
- DDL
- messages 
    - please add something for my 998 & 998
    - you might want a generic err msg
- the final code for the Template stored proc
    - feel free to take mine and butcher it
    - XOR I can upgrade it once the above is complete

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Sorry to keep bothering you with low-level GitHub stuff.

Ok, I found it, it is intact
[Original](https://gist.github.com/DanielLoth/0599c2475368083acc9032d34f0919e1)

Now, wtf do I do to publish an upgrade to that ???

One that page, **Fork** creates a new something or other, not what I expected, and the formatting was horrible (my code is pre-formatted).  After fiddling for a while, I deleted it, which deleted the **Gist**, my Gist, not yours as I thought (above comments).  Phew.

Cheers
Derek

**Comment by DanielLoth** [comment]
Hi Derek, I replied to the comment in the Gist before coming here.

Forking a repository is essentially making your own copy of it. If you were using Git, and wanted to contribute to a project, you could:
1. Fork their repository
2. Working in your fork, make changes until you've implemented a fix / feature / etc
3. Raise a pull request from your fork into their repository to contribute your changes.

So if you clicked the fork button then it's quite harmless. It just means there's a copy of my repository under your user profile.

**Comment by DanielLoth** [comment]
Also, congratulations on the outcome on the outcome at the hearing.

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

> Also, congratulations on the outcome on the outcome at the hearing.

Thanks.  It did not happen, which is why I had had free time yesterday.  They folded the day before the hearing, causing me to withdraw the Appeal.  This is the problem when dealing with dishonest, dishonourable people.  They do not have the honour to lose cleanly, to let th eother party win cleanly, they drag it out as much as they can, even after losing.  Eg. they lost 60% at the initial Hearing, I Appealed to ensure the lost the remaining 40%, they dragged it out right up to the listed Appeal Hearing and folded the day before.  A mass of work on my part could have been saved if they were honest.

Now they think that they made only minor mistakes, so they are going to sue again.  Instead of waiting for that, I have to sue them first for dishonest conduct.  The rigmarole continues.

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Can I ask a personal favour, please.  Whereas interaction with you is straight-forward, and your c_d_t thread was closed in short order, interaction with Nicola is laborious and never-ending.  Are you keeping up with the posts on that thread ?  If so, could you please give me some feedback.  I am interested in how a developer such as you finds the content.

Also, about my strong wording, and defined references to insanity.

It is not that I am insecure about it, not at all, I have been destroying these idiots for twenty years.  It is more about how people other than academics perceive such threads (when they read it, years later, as they do).

Cheers
Derek

**Comment by DanielLoth** [comment]
@Derek-Asirvadem,

It looks like it's well and truly off-topic at this point. If I'm honest about it, I think the extra stuff detracts from the information content. For anyone easily offended, they're unlikely to continue reading. For everyone else, the main content is harder to parse.

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Yes, I need your honesty and frankness.

That is precisely what I was afraid of.

Nicola had hijacked the thread a couple of times, and I brought it back.  But this last time it got into the cause of the problems and confusion.  So I went for it.

Re being offended.  I couldn't care less.  I get a fair amount of emails thanking me for my "intellectual honesty" and for showing up the academics for what they are.  This is the last remaining public forum in which the academics engage.  (Which is why Nicola feels free to hijack the thread.)  The hijacks and dishonest argumentation (eg. Straw Man) are voluminous, taking them down is at least as voluminous.

How about we do this:
1. Start a new thread
    - either append **"II** to the title _Stored procedure structure in RDBMS using Lock Manager for transaction isolation_
    - or shorten it and add something like "for Developers".  Your thread, your choice.  
    - I would emphasise **SQL**, because the freeware & Oracle are not SQL complaint
2. Post the same first post, 
    - with the first line along the lines of "This contains the just the requirement and the result, without the academic discussion.  Please keep it to discussion "
    - minus the code
3. I will post an answer, with the conditions and qualifiers, and the Transaction Sanity doc (tomorrow).
4. Post a link to your final code

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Nah.  I will do it myself.

Cheers
Derek

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Yes, I need your honesty and frankness.

Re the Data Modellign task ... are you done, or do you wish to keep going ?  It seems Nicola is interested, he was very interested in the Movie Title DM task.  If you wish to keep going, should I link him to this PullRequest (I think that get him the whole repository) ?

Court docs are due.  After tonight, I am off the air until Sat.

Cheers
Derek

**Comment by DanielLoth** [comment]
Hi @Derek-Asirvadem,

I'm happy for you to share the link to the repository. It's public, so he'll be able to see it. Dunno how familiar he is with GitHub, but it might be worth mentioning that these pull requests contain the bulk of the information of interest.

I have started a V0_10 model here:
https://github.com/DanielLoth/ShootingClubDatabase/blob/main/Diagrams/Data%20model%20V0_10%20WIP.pdf

However it is incomplete, a work in progress. The bottom is the V0_6 and was just there for my reference while I restructure the V0_10 model.

Sorry, I've been spending more of my time on work stuff lately.

---

One key change I'd had in mind for V0_10 is that I no longer require mobile / email as part of `PersonFull`.

Reason being, the NSW *Firearms Regulation 2017 Part 9 Approval of clubs s97 (1) (a)* only calls for the following particulars for each member:
- Full name
- Date of birth
- Residential address.

Same story for *Part 6 s61 International visitors competition permit (3) (a)* which similarly calls for:
- Full name
- Date of birth
- Home address in the country in which the applicant ordinarily resides.

---

I also added `Competition`. In my earliest diagrams I had `Competition` as being identified by `Organisation`. In this one, my intent is to model `Competition` as independent. An `Organisation` will host that `Competition`.

---

Good luck with the court hearing.

Dan

**Comment by Derek-Asirvadem** [comment]
@DanielLoth 

Good work.

> However it is incomplete, a work in progress.

Before commenting, should I wait for **V0_10 WIP** to progress to a "final" **V0_10** ?

> Good luck with the court hearing.

Thanks, I need it.  It is doc submission for a new case, which has to be done before 21 Aug, not a hearing.

Cheers
Derek

**Pull request merged**
